server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # Teruskan API secara absolut (tanpa garis miring di akhir url backend)
    location /api/ {
        proxy_pass http://backend:3333;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
