version: '3.8'

services:
  backend:
    build: ./backend
    restart: always
    # Backend berjalan di jaringan internal Docker, tidak perlu expose port ke luar

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend/index.html:/usr/share/nginx/html/index.html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    restart: always
